library(bnlearn)
data <- read.csv("~/Downloads/student+performance/student/student-por.csv", sep=";")

data$school <- factor(data$school,levels = c("GP","MS"),labels=c("Gabriel Pereira","Mousinho da Silveira"))
data$sex <- factor(data$sex, levels = c("F","M"), labels = c("Female","Male"))
data$age <- factor(data$age)
data$address <- factor(data$address,levels=c("R","U"),labels=c("Rural","Urban"))
data$famsize <- factor(data$famsize,levels=c("LE3","GT3"),labels=c("Less or equal to 3","Greater than 3"))
data$Pstatus <- factor(data$Pstatus, levels=c("T","A"),labels=c("Living together", "Apart"))
data$Medu <- factor(data$Medu,levels=c(0,1,2,3,4),labels=c("None","Primary Education","5th to 9th Grade","Secondary Education","Higher Education"))
data$Fedu <- factor(data$Fedu,levels=c(0,1,2,3,4),labels=c("None","Primary Education","5th to 9th Grade","Secondary Education","Higher Education"))
data$Mjob <- factor(data$Mjob,levels=c("at_home","health","other","services","teacher"),labels=c("At Home","Healtcare Related","Other","Civil Services","Teacher"))
data$Fjob <- factor(data$Fjob,levels=c("at_home","health","other","services","teacher"),labels=c("At Home","Healtcare Related","Other","Civil Services","Teacher"))
data$reason <- factor(data$reason,levels=c("home","reputation","course","other"),labels=c("Close to Home","School Reputation","Course Preference","Other"))
data$guardian <- factor(data$guardian, levels=c("mother","father","other"),labels=c("Mother","Father","Other"))
data$traveltime <- factor(data$traveltime,levels=c(1,2,3,4),labels=c("Less than 15min","15 to 30 mins", "30 mins to 1 hour","More than 1 hour"))
data$studytime <- factor(data$studytime,levels=c(1,2,3,4),labels=c("Less than 2 hours","2 to 5 hours", "5 to 10 hours","More than 10 hours"))
data$failures <- factor(data$failures)
data$schoolsup <- factor(data$schoolsup)
data$famsup <- factor(data$famsup)
data$paid <- factor(data$paid)
data$activities <- factor(data$activities)
data$nursery <- factor(data$nursery)
data$higher <- factor(data$higher)
data$internet <- factor(data$internet)
data$romantic <- factor(data$romantic)
data$famrel <- factor(data$famrel ,levels=c(1,2,3,4,5),labels=c("Very Bad","Bad","Ok","Good","Excellent"))
data$freetime <-  factor(data$freetime,levels=c(1,2,3,4,5),labels=c("Very Low","Low","Medium","High","Very High"))
data$goout <- factor(data$goout,levels=c(1,2,3,4,5),labels=c("Very Low", "Low","Medium","High","Very High"))
data$Dalc <- factor(data$Dalc,levels=c(1,2,3,4,5),labels=c("Very Low", "Low","Medium","High","Very High"))
data$Walc <- factor(data$Walc,levels=c(1,2,3,4,5),labels=c("Very Low", "Low","Medium","High","Very High"))
data$health <- factor(data$health ,levels=c(1,2,3,4,5),labels=c("Very Bad","Bad","Ok","Good","Excellent"))
data$G3 <- factor(cut(data$G3,breaks=c(-1000,9.99999999,100000),labels=c("< 10", ">= 10")))
data$G2 <- factor(cut(data$G2,breaks=c(-1000,9.99999999,100000),labels=c("< 10", ">= 10")))
data$G1 <- factor(cut(data$G1,breaks=c(-1000,9.99999999,100000),labels=c("< 10", ">= 10")))
data$absences <- factor(cut(data$absences,breaks=c(-1000,5.1,20.1,10000),labels=c("0-5","6-20","More than 20")))
colnames(data)[33] <- "class"



dag <- model2network("[famsup][activities][paid][goout][sex|famsup:activities][schoolsup|sex][school|schoolsup][G1|sex:school][address|school][reason|school][failures|G1][G2|G1][traveltime|address][internet|address:school][age|failures][class|G2:G1][Mjob|internet][higher|G1:age][guardian|age][romantic|age][Medu|Mjob][Pstatus|guardian][famsize|Pstatus][nursery|famsize][Fedu|Medu][Fjob|Fedu]")

data <- data[,nodes(dag)]

student1 <-bn.fit(dag,data)
usethis::use_data(student1,overwrite=T)


data <- read.csv("~/Downloads/student+performance/student/student-mat.csv", sep=";")

data$school <- factor(data$school,levels = c("GP","MS"),labels=c("Gabriel Pereira","Mousinho da Silveira"))
data$sex <- factor(data$sex, levels = c("F","M"), labels = c("Female","Male"))
data$age <- factor(data$age)
data$address <- factor(data$address,levels=c("R","U"),labels=c("Rural","Urban"))
data$famsize <- factor(data$famsize,levels=c("LE3","GT3"),labels=c("Less or equal to 3","Greater than 3"))
data$Pstatus <- factor(data$Pstatus, levels=c("T","A"),labels=c("Living together", "Apart"))
data$Medu <- factor(data$Medu,levels=c(0,1,2,3,4),labels=c("None","Primary Education","5th to 9th Grade","Secondary Education","Higher Education"))
data$Fedu <- factor(data$Fedu,levels=c(0,1,2,3,4),labels=c("None","Primary Education","5th to 9th Grade","Secondary Education","Higher Education"))
data$Mjob <- factor(data$Mjob,levels=c("at_home","health","other","services","teacher"),labels=c("At Home","Healtcare Related","Other","Civil Services","Teacher"))
data$Fjob <- factor(data$Fjob,levels=c("at_home","health","other","services","teacher"),labels=c("At Home","Healtcare Related","Other","Civil Services","Teacher"))
data$reason <- factor(data$reason,levels=c("home","reputation","course","other"),labels=c("Close to Home","School Reputation","Course Preference","Other"))
data$guardian <- factor(data$guardian, levels=c("mother","father","other"),labels=c("Mother","Father","Other"))
data$traveltime <- factor(data$traveltime,levels=c(1,2,3,4),labels=c("Less than 15min","15 to 30 mins", "30 mins to 1 hour","More than 1 hour"))
data$studytime <- factor(data$studytime,levels=c(1,2,3,4),labels=c("Less than 2 hours","2 to 5 hours", "5 to 10 hours","More than 10 hours"))
data$failures <- factor(data$failures)
data$schoolsup <- factor(data$schoolsup)
data$famsup <- factor(data$famsup)
data$paid <- factor(data$paid)
data$activities <- factor(data$activities)
data$nursery <- factor(data$nursery)
data$higher <- factor(data$higher)
data$internet <- factor(data$internet)
data$romantic <- factor(data$romantic)
data$famrel <- factor(data$famrel ,levels=c(1,2,3,4,5),labels=c("Very Bad","Bad","Ok","Good","Excellent"))
data$freetime <-  factor(data$freetime,levels=c(1,2,3,4,5),labels=c("Very Low","Low","Medium","High","Very High"))
data$goout <- factor(data$goout,levels=c(1,2,3,4,5),labels=c("Very Low", "Low","Medium","High","Very High"))
data$Dalc <- factor(data$Dalc,levels=c(1,2,3,4,5),labels=c("Very Low", "Low","Medium","High","Very High"))
data$Walc <- factor(data$Walc,levels=c(1,2,3,4,5),labels=c("Very Low", "Low","Medium","High","Very High"))
data$health <- factor(data$health ,levels=c(1,2,3,4,5),labels=c("Very Bad","Bad","Ok","Good","Excellent"))
data$G3 <- factor(cut(data$G3,breaks=c(-1000,9.99999999,100000),labels=c("< 10", ">= 10")))
data$G2 <- factor(cut(data$G2,breaks=c(-1000,9.99999999,100000),labels=c("< 10", ">= 10")))
data$G1 <- factor(cut(data$G1,breaks=c(-1000,9.99999999,100000),labels=c("< 10", ">= 10")))
data$absences <- factor(cut(data$absences,breaks=c(-1000,5.1,20.1,10000),labels=c("0-5","6-20","More than 20")))
colnames(data)[33] <- "class"

dag <- model2network("[goout][nursery][activities][reason][Pstatus][G2][class|G2][famsize|Pstatus][failures|G2][higher|failures][age|failures][paid|higher][sex|higher][school|age][guardian|age][romantic|age][famsup|paid:school][address|school][schoolsup|school][G1|schoolsup:G2][internet|famsup:address][traveltime|address][Mjob|internet][Medu|Mjob][Fedu|Medu][Fjob|Fedu]")

data <- data[,nodes(dag)]

student2 <-bn.fit(dag,data)
usethis::use_data(student2,overwrite=T)
